[package]
name = "rust-cli-binary"
version = "0.1.0"
edition = "2021"

# Metadata for creating a library
[lib]
name = "mylib"           # The library name; can be omitted if matching package name
path = "src/lib.rs"
crate-type = ["lib"]     # Explicitly specifies library type

# Dependencies
[dependencies]
rand = "0.8.5"           # For random number generation
csv = "1.3.0"            # For reading/writing CSV files
serde = { version = "1.0", features = ["derive"] } # Ensures Serde's derive macro for serialization
reqwest = { version = "0.11.22", features = ["blocking"] } # For HTTP requests
rusqlite = "0.29.0"      # For SQLite database interaction
lazy_static = "1.4.0"    # For defining static data structures at runtime
