name: Rust CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Verify Project Structure
        run: |
          echo "Checking for Cargo.toml and src directory contents"
          ls rust_cli_binary/Cargo.toml  # Verify Cargo.toml exists
          ls rust_cli_binary/src         # Verify src directory exists and contains required files

      - name: Build Rust
        run: cargo build --release
        working-directory: rust_cli_binary

      - name: List contents of target directory
        run: ls rust_cli_binary/target  # Check if target directory exists

      - name: List contents of release directory
        run: ls rust_cli_binary/target/release  # Check if release directory was created

      - name: Prepare binary artifact
        run: |
          mkdir -p data
          cp rust_cli_binary/target/release/rust_cli_binary data/  # Adjust binary name if different

      - name: Upload binary artifact to GitHub
        uses: actions/upload
