name: Rust CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Build Rust
        run: make release

      - name: Format the Code
        run: make format

      - name: Make Lint
        run: make lint

      - name: Make Test
        run: make test

      - name: List release directory
        run: ls rust_cli_binary/target/release  # Debug step to confirm binary name

      - name: Prepare binary artifact
        run: mkdir -p data && cp rust_cli_binary/target/release/Eric_Ortega_Rodriguez_Individual_Project_2 ./data/ 
      - name: Upload binary artifact to GitHub
        uses: actions/upload-artifact@v4  # This action uploads the artifact
        with:
          name: Eric_Ortega_Rodriguez_Individual_Project_2  # Artifact name
          path: data/Eric_Ortega_Rodriguez_Individual_Project_2  # Path to the binary
