name: Rust CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Verify Project Structure
        run: |
          echo "Checking Cargo.toml and src directory"
          ls rust_cli_binary/Cargo.toml  # Check if Cargo.toml exists
          ls rust_cli_binary/src         # Check if src directory and files exist

      - name: Build Rust
        run: cargo build --release
        working-directory
